# Generated by Django 5.2.8 on 2025-12-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='creator',
            new_name='owner',
        ),
    ]
