# Generated by Django 5.2.8 on 2025-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_rename_creator_habit_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reminder_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for the scheduled reminder",
                max_length=255,
                null=True,
            ),
        ),
    ]
